CREATE TABLE t_permission (
id BIGSERIAL PRIMARY KEY,
name VARCHAR(50) UNIQUE NOT NULL
);

CREATE TABLE t_user (
id BIGSERIAL PRIMARY KEY,
email VARCHAR(255) UNIQUE NOT NULL,
password VARCHAR(255) NOT NULL
);

CREATE TABLE t_user_permissions (
user_id BIGINT NOT NULL,
permission_id BIGINT NOT NULL,
PRIMARY KEY (user_id, permission_id),
FOREIGN KEY (user_id) REFERENCES t_user(id) ON DELETE CASCADE,
FOREIGN KEY (permission_id) REFERENCES t_permission(id) ON DELETE CASCADE
);